# TF Syntax Basic

In [1]:
import tensorflow as tf

c:\users\devan\appdata\local\programs\python\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.6.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello)

In [9]:
print(result)

b'Hello '


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result)

b'Hello World'


In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(40)

In [15]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
a

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess :
    result = sess.run(a+b)

In [18]:
result

50

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [22]:
tf.Session().run(fill_mat)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [23]:
myzeros = tf.zeros((4,4))

In [24]:
myones = tf.ones((4,4))

In [35]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [36]:
tf.Session().run(myrandn)

array([[-0.9352399 ,  0.25161126, -0.6147482 , -0.42883292],
       [ 2.166326  , -0.45085394,  0.720204  , -1.1253867 ],
       [-0.8081904 ,  0.01019565,  1.6764833 ,  0.34897256],
       [-0.7544426 , -2.0465927 ,  0.38164002,  0.79314053]],
      dtype=float32)

In [39]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [40]:
tf.Session().run(myrandu)

array([[0.0763334 , 0.27872753, 0.6768167 , 0.3518623 ],
       [0.3188138 , 0.23054063, 0.42023885, 0.49695432],
       [0.7699568 , 0.525172  , 0.5575286 , 0.47737777],
       [0.44889796, 0.60461974, 0.07326436, 0.22375655]], dtype=float32)

In [41]:
my_ops = [const,myzeros,myones,myrandn,myrandu]

In [42]:
my_ops

[<tf.Tensor 'Const_4:0' shape=() dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>]

In [43]:
sess = tf.InteractiveSession()

In [44]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0.17710578 0.28765917 0.96428204 0.63925815]
 [0.9536841  0.71821964 0.15805805 0.6028173 ]
 [0.55910444 0.35971618 0.719504   0.56583095]
 [0.00138903 0.10109115 0.09295905 0.65096796]]


[[0.7293223  0.7796093  0.14622009 0.19691026]
 [0.17099833 0.7316077  0.4294871  0.95451665]
 [0.97475696 0.11995959 0.07202649 0.04754186]
 [0.221879   0.19182408 0.14459407 0.26485562]]




In [45]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0.96164596 0.49554992 0.99620724 0.17130566]
 [0.37210906 0.69739246 0.37465    0.67480433]
 [0.28744185 0.3112067  0.29653966 0.8857454 ]
 [0.13797545 0.04171884 0.86912286 0.49308157]]


[[0.7686554  0.3990171  0.8825145  0.4583094 ]
 [0.87581515 0.2807039  0.18665266 0.3159318 ]
 [0.8265164  0.9375305  0.15217948 0.47481215]
 [0.8862227  0.5876441  0.5615016  0.7261206 ]]




In [47]:
a = tf.constant([[1,2],
                [3,4]])

In [48]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [49]:
b = tf.constant([[10],[100]])

In [50]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [52]:
result = tf.matmul(a,b)

In [53]:
sess.run(result)

array([[210],
       [430]])

In [54]:
result.eval()

array([[210],
       [430]])